### ISSUE TITLE
Proxy authorization

### ISSUE THREAD

**Issue by SergeyKorotaev** [zhenyolka/DPITunnel#12]
greetings. and how to configure authorization for a proxy?

**Comment by zhenyolka** [comment]
Надо будет добавить. Как будет время, сделаю: там сложного ничего нет, вроде.

**Comment by zhenyolka** [comment]
Добавлено. 
Коммит уже в мастер ветке, но релиза еще нет. Если не хотите собирать сами, вот apk: https://dropmefiles.com/IWe7N
