### ISSUE TITLE
cannot download ca

### ISSUE THREAD

**Issue by A-userfromtheforum** [zhenyolka/DPITunnel#13]
I wanted to spoof sni so i clicked a link in the app and it gave me 404 error

**Comment by zhenyolka** [comment]
One certificate for all users is secutiry lack, so I decided to generate certificate locally at first program start and remove that certificate.
Use this apk (it's not released yet): https://dropmefiles.com/IWe7N
Remove old version before install it

**Comment by kimpig** [comment]
I have same problem. Can you share with me too?
