### ISSUE TITLE
ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by dreemdealer** [zhenyolka/DPITunnel#15]
I have installed DPI tunnel time a go on my galaxy not 4, at that time my mobile was root , after getting system update , i just want to uninstall but without DPI tunnel app my network won't work , chrome always show error ( no network ,  ERR_PROXY_CONNECTION_FAILED) even my mobile is connected to wifi network , please help me .. 
Note: after updating my mobile no more rooted,

**Comment by zhenyolka** [comment]
You must to press ON/OFF button before uninstall. If you didn't do it, run AS ROOT this command "settings put global http_proxy :0"

**Comment by dreemdealer** [comment]
Yeah i didn't do on of before uninstall , and now my mobile isn't rooted ,

**Comment by zhenyolka** [comment]
You must root it. There is no other way exclude root or factory reset.
If don't know what can happen and how phone works, don't use root next time. DPITunnel supports non-root Vpn service mode.

**Comment by dreemdealer** [comment]
Ok , and after root how to put command ,"settings put global http_proxy :0"

**Comment by zhenyolka** [comment]
Open terminal, run "su" to get root, then run my command. Run commands without ""
