### ISSUE TITLE
Start the service even if the host lista can't be downloaded

### ISSUE THREAD

**Issue by licaon-kter** [zhenyolka/DPITunnel#2]
Not sure if it warrants such a brutal option _(hey maybe the user is in a network that blocks that and needs your app to bypass even that?)_...

**Comment by zhenyolka** [comment]
All is ok. To start service without hostlist you need to unset "Use hostlist" and maybe "Use DoH protocol only for sites in hostlist".

**Comment by licaon-kter** [comment]
Yes, but that's not clear, you only get a pop-up with "unable to download" that doesn't say anything about "the need to need to unset this and maybe that too".
