### ISSUE TITLE
provide console binaries also

### ISSUE THREAD

**Issue by DI555** [zhenyolka/DPITunnel#4]
i'd like to ask about very useful thing about console binaries, exactly the same way like tor, dnscrypt and purple_i2p for example, - without a gui but with a config file. Please, so it would be possible using DPITunnel in a very powerful ways !!!
(btw, wich project app(s) sources are you using as a basic proxy here ?)

**Comment by zhenyolka** [comment]
Thanks for issue! First, my app is written from scratch, all code is mine.
Second, what binaries are you asking for? Arm linux, or android. I ask about it, because android ndk don't support https connections (now i do it with java code, but android binaries can't use java code).

**Comment by DI555** [comment]
was asking about android ones and the same way, like android tor or dnscrypt for example...  yes, it seems in binaries not to be possi le any java...:((
but nevertheless the goal was to be possible integration to the InviZible app as a new module...

**Comment by zhenyolka** [comment]
I will close issue because it isn't possible to provide binaries because of java code.

**Comment by DI555** [comment]
yes, sure. but maybe... what about disparting code for core one and gui one ? it may be very useful if will be plans for linux version for example...

**Comment by zhenyolka** [comment]
Core part use java to connect to doh servers, so i cant remove java from code part
