### ISSUE TITLE
advanced DoH template urls support

### ISSUE THREAD

**Issue by DI555** [zhenyolka/DPITunnel#5]
first of all let me thank you for the DPITunnel , it was very awaited!!!

 now would like to ask about advanced DoH template urls support(i'm not sure if not yet) and combinations,
 it's support of links like ''https://server(or_adress)/dns-query'' and entering one or more(!) space-separated DoH template urls.
 and also great to be support of just urls like ''https://server(or_adress)'' or just ''server(or_adress)'' with entering one or more(!) space-separated urls.

**Comment by zhenyolka** [comment]
Added support of several DoH servers separated by new line. Check releases
