### ISSUE TITLE
specific blocked site not loaded

### ISSUE THREAD

**Issue by sabitmaulana** [zhenyolka/DPITunnel#6]
Hi. First of all, thanks for making this app. This is great!

This application work perfectly and i can access many sites that blocked by my ISP. But, a little problem that made me itchy.
My ISP block reddit.com. When using dpitunnel, the other blocked sites can be accessed except this one. I think this is not dpitunnel problem and i'm sorry if i asking this here. But, can you guide me to inspect what's the problem is?

My device is Redmi 4A using android 6 (rooted). i'm using default setting with hostlist unchecked and set dpitunnel proxy to work globally. You can ask me if you need more information

**Comment by zhenyolka** [comment]
If think you aren't from Russia. What country?
Sometimes, usually in Russia, there is several dpi's beetween you and site. You can bypass for example first, second, but can't bypass fourth or fifth. You need to try using other dpi bypass options such as socks5 proxyfing.

**Comment by sabitmaulana** [comment]
I'm from Indonesia. So, different site have different amount of dpi's? Cause the other site works as expected. Thanks for your suggestion too. I'll check it out
