### ISSUE TITLE
Doesn't work - Android 10, see below

### ISSUE THREAD

**Issue by Evergardener** [zhenyolka/DPITunnel#7]
Doesn't work on Android 10.
Latest updates installed on Pixel.
Can't enable the service.
Root is present.
All permissions are given.
Also there was a problem updating hosts list.
![IMG_20200729_102222_352](https://user-images.githubusercontent.com/67442100/88764375-eb7e4d00-d185-11ea-88bd-a30c6d8bfb06.gif)

**Comment by zhenyolka** [comment]
Hi! Just interesting, what country?
There is a problem while updating hostlist, so it can't start.
You need to disable "Use hostlist" and try to start DPITunnel.
P.S. Next time please send logcat. I am not psychic.

**Comment by Evergardener** [comment]
It worked by disabling hosts file but browsing speed is too low for my connection.
Slower than a VPN.
Sometimes I get timeout.
Where to get log file, looked in internal memory, didn't find any .log files associated with DPITunnel?

**Comment by zhenyolka** [comment]
DPITunnel logs to logcat. It isn't file.
I think you use VPN mode and root mode same time. You need to disable VPN mode and use only root mode. It will increase speed. If you have questions ask in telegram group.

**Comment by Evergardener** [comment]
Проверил только со включенным VPN и повсеместным в режиме рута, то же самое.
Приложил logcat:
[logcat.txt](https://github.com/zhenyolka/DPITunnel/files/4999236/logcat.txt)
