### ISSUE TITLE
HTTPS Tunnel

### ISSUE THREAD

**Issue by DRSDavidSoft** [zhenyolka/DPITunnel#8]
Can you please provide support for **HTTPS** (not HTTP) proxy tunnel?

Currently, only plain HTTP proxy is supported.  It would be nice if DPI Tunnel could make proxy connections over SSL/TLS Proxy in addition to that.

**Comment by zhenyolka** [comment]
I will add this feature maybe, but pull request from you will be better.

**Comment by zhenyolka** [comment]
I added this feature. You may build from repository yourself or wait for new version.
