### ISSUE TITLE
Says "there was an error updating hostlist" and when on is pressed, crashes.

### ISSUE THREAD

**Issue by ilazim** [zhenyolka/DPITunnel#9]

**Comment by zhenyolka** [comment]
Are you from Russia? If yes, try to press on Update hostlist. If no, just disable hostlist by disabling option Use hostlist.

**Comment by ilazim** [comment]
Ahh guess that should do it. Also do I use the inbuilt browser or does it work on all other apps/browsers?

**Comment by zhenyolka** [comment]
By default with VPN mode it works with all apps. When you press start it asks for VPN connection.

**Comment by zhenyolka** [comment]
Can I close issue?
